[package]
name = "df_native"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "2", features = ["serde-json", "napi6"] }
napi-derive = "2"
sysinfo = "0.30"
serde = { version = "1.0", features = ["derive"] }


[build-dependencies]
napi-build = "2"
