/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface FsStat {
  fstype: string
  source: string
  size: bigint
  used: bigint
  avail: bigint
  pcent: number
  target: string
}
export declare function df(): Array<FsStat>
